import path from "path";
import fs from "fs";

// Load the compiled server.cjs generated by Vite + esbuild
const serverPath = path.join(__dirname, "dist", "server.cjs");

if (fs.existsSync(serverPath)) {
  require(serverPath);
} else {
  console.error("Error: dist/server.cjs not found. Please run 'npm run build' first.");
  process.exit(1);
}
