<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #222222;
						margin: 0;
						padding: 20px 24px;
						background-color: #ffffff;
					}
					a {
						color: #111111;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.header {
						margin-bottom: 16px;
						padding-bottom: 12px;
						border-bottom: 1px solid #e5e7eb;
					}
					h1 {
						font-size: 24px;
						color: #111111;
						margin: 0 0 6px;
						font-weight: 700;
					}
					.expl {
						margin: 8px 0;
						line-height: 1.5;
						font-size: 13px;
						color: #555555;
					}
					.expl a {
						color: #111111;
						font-weight: 600;
						text-decoration: underline;
					}
					.btn-back {
						display: inline-block;
						font-weight: 600;
						font-size: 13px;
						color: #111111;
						margin-bottom: 10px;
					}
					.btn-back:hover {
						text-decoration: underline;
					}
					#content {
						margin: 0 auto;
						width: 100%;
					}
					table {
						border: none;
						border-collapse: collapse;
						font-size: 13px;
						margin: 10px 0 30px;
						width: 100%;
						background: #ffffff;
						border-top: 1px solid #cccccc;
					}
					th {
						text-align: left;
						padding: 6px 10px;
						font-size: 12px;
						font-weight: 600;
						color: #444444;
						border-bottom: 1px solid #cccccc;
						background: #fafafa;
					}
					th.num, td.num {
						text-align: center;
						width: 70px;
					}
					th.date, td.date {
						text-align: left;
						width: 220px;
						white-space: nowrap;
					}
					td {
						padding: 5px 10px;
						vertical-align: middle;
						color: #222222;
						border: none;
					}
					tbody tr:nth-child(even) {
						background-color: #ededed;
					}
					tbody tr:nth-child(odd) {
						background-color: #ffffff;
					}
					tbody tr:hover {
						background-color: #e2e2e2;
					}
					.badge-counter {
						font-weight: 700;
						color: #111111;
					}
				</style>
			</head>
			<body>
				<div id="content">
					<div class="header">
						<h1>XML Sitemap</h1>
						<p class="expl">
							Generated by <strong>Yoast SEO</strong>, this is an XML Sitemap, meant for consumption by search engines.<br/>
							You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener noreferrer">sitemaps.org</a>.
						</p>
					</div>

					<xsl:if test="sitemap:sitemapindex">
						<p class="expl">
							This XML Sitemap Index file contains <span class="badge-counter"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></span> sitemaps.
						</p>
						<table id="sitemap" cellpadding="0" cellspacing="0">
							<thead>
								<tr>
									<th width="75%">Sitemap</th>
									<th class="date" width="25%">Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<xsl:variable name="sitemapUrl">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<tr>
										<td>
											<a href="{$sitemapUrl}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td class="date">
											<xsl:choose>
												<xsl:when test="contains(sitemap:lastmod, 'T')">
													<xsl:value-of select="concat(substring(sitemap:lastmod, 1, 10), ' ', substring(sitemap:lastmod, 12, 5), ' +00:00')"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="concat(sitemap:lastmod, ' 00:00 +00:00')"/>
												</xsl:otherwise>
											</xsl:choose>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<xsl:if test="sitemap:urlset">
						<p class="expl">
							<a href="/sitemap_index.xml" class="btn-back">&#8592; Sitemap Index</a>
						</p>
						<p class="expl">
							This XML Sitemap contains <span class="badge-counter"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></span> URLs.
						</p>
						<table id="sitemap" cellpadding="0" cellspacing="0">
							<thead>
								<tr>
									<th width="75%">URL</th>
									<th class="num" width="10%">Images</th>
									<th class="date" width="15%">Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<xsl:variable name="itemURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<tr>
										<td>
											<a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td class="num">
											<xsl:value-of select="count(image:image)"/>
										</td>
										<td class="date">
											<xsl:choose>
												<xsl:when test="contains(sitemap:lastmod, 'T')">
													<xsl:value-of select="concat(substring(sitemap:lastmod, 1, 10), ' ', substring(sitemap:lastmod, 12, 5), ' +00:00')"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="concat(sitemap:lastmod, ' 00:00 +00:00')"/>
												</xsl:otherwise>
											</xsl:choose>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>