import React, { useState, useEffect } from "react";
import { BlogPost, CustomPage, SupportedLanguage } from "../../types";
import {
  loadRobotsTxt,
  saveRobotsTxt,
  buildDefaultRobotsTxt,
  buildDynamicSitemapXml,
  loadSitemapXml,
  saveSitemapXml,
} from "../../data/siteConfig";
import { loadCustomPages } from "../../data/customPagesData";
import {
  Globe,
  FileCode,
  Check,
  Copy,
  Download,
  ExternalLink,
  Sparkles,
  Save,
  RotateCcw,
  Sliders,
  ShieldCheck,
  AlertCircle,
  FileText,
  Search,
  CheckCircle2,
  RefreshCw,
} from "lucide-react";

interface AdminSeoCrawlerProps {
  posts?: BlogPost[];
  customPages?: CustomPage[];
}

export function AdminSeoCrawler({ posts = [], customPages = [] }: AdminSeoCrawlerProps) {
  const [activeSubTab, setActiveSubTab] = useState<"robots" | "sitemap">("robots");

  // ROBOTS.TXT STATE
  const [robotsContent, setRobotsContent] = useState<string>("");
  const [robotsUserAgent, setRobotsUserAgent] = useState<string>("*");
  const [allowAllCrawling, setAllowAllCrawling] = useState<boolean>(true);
  const [disallowAdmin, setDisallowAdmin] = useState<boolean>(true);
  const [disallowApi, setDisallowApi] = useState<boolean>(true);
  const [disallowTemp, setDisallowTemp] = useState<boolean>(true);
  const [crawlDelay, setCrawlDelay] = useState<string>("none");
  const [customDisallowRules, setCustomDisallowRules] = useState<string>("");
  const [sitemapUrlDirective, setSitemapUrlDirective] = useState<string>("");
  const [robotsSavedSuccess, setRobotsSavedSuccess] = useState<boolean>(false);
  const [robotsCopied, setRobotsCopied] = useState<boolean>(false);
  const [isRobotsSyncing, setIsRobotsSyncing] = useState<boolean>(false);

  // SITEMAP.XML STATE
  const [sitemapContent, setSitemapContent] = useState<string>("");
  const [sitemapDomain, setSitemapDomain] = useState<string>("");
  const [incCorePages, setIncCorePages] = useState<boolean>(true);
  const [incLanguages, setIncLanguages] = useState<boolean>(true);
  const [incBlogPosts, setIncBlogPosts] = useState<boolean>(true);
  const [incCustomPages, setIncCustomPages] = useState<boolean>(true);
  const [defaultChangeFreq, setDefaultChangeFreq] = useState<"daily" | "weekly" | "monthly">("daily");
  const [defaultPriority, setDefaultPriority] = useState<string>("1.0");
  const [sitemapSavedSuccess, setSitemapSavedSuccess] = useState<boolean>(false);
  const [sitemapCopied, setSitemapCopied] = useState<boolean>(false);
  const [isSitemapSyncing, setIsSitemapSyncing] = useState<boolean>(false);

  // Load initial content from server & fallback to localStorage
  useEffect(() => {
    const origin = typeof window !== "undefined" ? window.location.origin : "https://scribddownloader.org";
    setSitemapDomain(origin);
    setSitemapUrlDirective(`${origin}/sitemap.xml`);

    // Fetch live robots.txt from server
    fetch("/api/seo/robots")
      .then((res) => res.json())
      .then((data) => {
        if (data.content) {
          setRobotsContent(data.content);
        } else {
          setRobotsContent(loadRobotsTxt(origin));
        }
      })
      .catch(() => {
        setRobotsContent(loadRobotsTxt(origin));
      });

    // Fetch live sitemap.xml from server
    fetch("/api/seo/sitemap")
      .then((res) => res.json())
      .then((data) => {
        if (data.content) {
          setSitemapContent(data.content);
        } else {
          const effectivePages = customPages.length > 0 ? customPages : loadCustomPages();
          setSitemapContent(loadSitemapXml(origin, posts, effectivePages));
        }
      })
      .catch(() => {
        const effectivePages = customPages.length > 0 ? customPages : loadCustomPages();
        setSitemapContent(loadSitemapXml(origin, posts, effectivePages));
      });
  }, []);

  // -------------------------------------------------------------
  // BUILD ROBOTS.TXT
  // -------------------------------------------------------------
  const handleBuildRobots = () => {
    const origin = sitemapDomain || (typeof window !== "undefined" ? window.location.origin : "");
    const lines: string[] = [
      `# robots.txt for Scribd Downloader`,
      `# Auto-generated by Admin SEO Controller on ${new Date().toISOString().split("T")[0]}`,
      ``,
      `User-agent: ${robotsUserAgent || "*"}`,
    ];

    if (allowAllCrawling) {
      lines.push(`Allow: /`);
    }

    if (crawlDelay !== "none") {
      lines.push(`Crawl-delay: ${crawlDelay}`);
    }

    if (disallowAdmin) {
      lines.push(``);
      lines.push(`# Disallow Admin and Management Consoles`);
      lines.push(`Disallow: /admin123`);
      lines.push(`Disallow: /admin`);
      lines.push(`Disallow: /admin/*`);
    }

    if (disallowApi) {
      lines.push(``);
      lines.push(`# Disallow API Endpoints`);
      lines.push(`Disallow: /api/`);
    }

    if (disallowTemp) {
      lines.push(``);
      lines.push(`# Disallow Transient Processing Directories`);
      lines.push(`Disallow: /temp_downloads/`);
    }

    if (customDisallowRules.trim()) {
      lines.push(``);
      lines.push(`# Custom Directives`);
      const extraRules = customDisallowRules.split("\n").map((r) => r.trim()).filter(Boolean);
      for (const rule of extraRules) {
        if (!rule.startsWith("Disallow:") && !rule.startsWith("Allow:")) {
          lines.push(`Disallow: ${rule.startsWith("/") ? rule : `/${rule}`}`);
        } else {
          lines.push(rule);
        }
      }
    }

    lines.push(``);
    lines.push(`# Official XML Sitemap Location`);
    lines.push(`Sitemap: ${sitemapUrlDirective || `${origin}/sitemap.xml`}`);
    lines.push(``);

    const generated = lines.join("\n");
    setRobotsContent(generated);
  };

  // SAVE & DEPLOY ROBOTS.TXT
  const handleSaveRobots = async () => {
    setIsRobotsSyncing(true);
    saveRobotsTxt(robotsContent);

    try {
      await fetch("/api/seo/robots", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: robotsContent }),
      });
      setRobotsSavedSuccess(true);
      setTimeout(() => setRobotsSavedSuccess(false), 3500);
    } catch (e) {
      console.error(e);
      setRobotsSavedSuccess(true);
      setTimeout(() => setRobotsSavedSuccess(false), 3500);
    } finally {
      setIsRobotsSyncing(false);
    }
  };

  const handleCopyRobots = () => {
    navigator.clipboard.writeText(robotsContent);
    setRobotsCopied(true);
    setTimeout(() => setRobotsCopied(false), 2000);
  };

  const handleResetRobots = () => {
    const def = buildDefaultRobotsTxt(sitemapDomain);
    setRobotsContent(def);
  };

  // -------------------------------------------------------------
  // BUILD SITEMAP.XML
  // -------------------------------------------------------------
  const handleBuildSitemap = () => {
    const origin = sitemapDomain.replace(/\/$/, "") || (typeof window !== "undefined" ? window.location.origin : "");
    const today = new Date().toISOString().split("T")[0];
    const languages: SupportedLanguage[] = incLanguages ? ["en", "br", "es", "fr", "de", "id"] : ["en"];

    const coreRoutes = [
      { path: "", priority: defaultPriority, changefreq: defaultChangeFreq },
      { path: "how-it-works", priority: "0.8", changefreq: "weekly" },
      { path: "blog", priority: "0.9", changefreq: "daily" },
      { path: "about", priority: "0.7", changefreq: "monthly" },
      { path: "contact", priority: "0.6", changefreq: "monthly" },
      { path: "privacy", priority: "0.5", changefreq: "monthly" },
      { path: "terms", priority: "0.5", changefreq: "monthly" },
    ];

    const xmlEntries: string[] = [];

    // Root entry
    xmlEntries.push(`  <url>
    <loc>${origin}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${defaultChangeFreq}</changefreq>
    <priority>${defaultPriority}</priority>
  </url>`);

    // 1. Core pages
    if (incCorePages) {
      for (const lang of languages) {
        for (const r of coreRoutes) {
          const fullPath = r.path ? `/${lang}/${r.path}` : `/${lang}`;
          xmlEntries.push(`  <url>
    <loc>${origin}${fullPath}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`);
        }
      }
    }

    // 2. Blog Posts
    if (incBlogPosts) {
      for (const post of posts) {
        if (post.status === "draft") continue;
        const postLang = (post.language as string) || "en";
        xmlEntries.push(`  <url>
    <loc>${origin}/${postLang}/blog/${post.slug}</loc>
    <lastmod>${post.date || today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>`);
      }
    }

    // 3. Custom Pages
    if (incCustomPages) {
      const effectivePages = customPages.length > 0 ? customPages : loadCustomPages();
      for (const page of effectivePages) {
        if (page.status === "draft") continue;
        const pageLang = page.language && page.language !== "all" ? page.language : "en";
        xmlEntries.push(`  <url>
    <loc>${origin}/${pageLang}/${page.slug}</loc>
    <lastmod>${page.lastModified || today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`);
      }
    }

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${xmlEntries.join("\n")}
</urlset>`;

    setSitemapContent(xml);
  };

  // SAVE & DEPLOY SITEMAP.XML
  const handleSaveSitemap = async () => {
    setIsSitemapSyncing(true);
    saveSitemapXml(sitemapContent);

    try {
      await fetch("/api/seo/sitemap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: sitemapContent }),
      });
      setSitemapSavedSuccess(true);
      setTimeout(() => setSitemapSavedSuccess(false), 3500);
    } catch (e) {
      console.error(e);
      setSitemapSavedSuccess(true);
      setTimeout(() => setSitemapSavedSuccess(false), 3500);
    } finally {
      setIsSitemapSyncing(false);
    }
  };

  const handleCopySitemap = () => {
    navigator.clipboard.writeText(sitemapContent);
    setSitemapCopied(true);
    setTimeout(() => setSitemapCopied(false), 2000);
  };

  const handleDownloadSitemap = () => {
    const blob = new Blob([sitemapContent], { type: "application/xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "sitemap.xml";
    a.click();
    URL.revokeObjectURL(url);
  };

  // Count URLs in sitemap
  const urlCountMatch = (sitemapContent.match(/<loc>/g) || []).length;

  return (
    <div className="space-y-6" id="admin-seo-crawler-manager">
      {/* Top Banner */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-600 bg-indigo-50 px-2.5 py-0.5 rounded-full border border-indigo-100 flex items-center gap-1.5">
              <Search className="w-3 h-3" />
              Search Engine Optimization
            </span>
            <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-700 bg-emerald-50 px-2.5 py-0.5 rounded-full border border-emerald-200 flex items-center gap-1">
              <CheckCircle2 className="w-3 h-3" />
              Live Endpoints Active
            </span>
          </div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 mt-1">
            robots.txt &amp; sitemap.xml Master Controller
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Build, edit, and instantly deploy live crawler rules and XML sitemaps to Googlebot, Bingbot, and web crawlers.
          </p>
        </div>

        {/* Live endpoint badges */}
        <div className="flex flex-wrap items-center gap-2">
          <a
            href="/robots.txt"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-indigo-50 text-slate-700 hover:text-indigo-600 text-xs font-bold border border-slate-200 transition cursor-pointer"
          >
            <span>/robots.txt</span>
            <ExternalLink className="w-3 h-3" />
          </a>
          <a
            href="/sitemap.xml"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-emerald-50 text-slate-700 hover:text-emerald-700 text-xs font-bold border border-slate-200 transition cursor-pointer"
          >
            <span>/sitemap.xml</span>
            <ExternalLink className="w-3 h-3" />
          </a>
        </div>
      </div>

      {/* Navigation Sub-Tabs */}
      <div className="flex items-center gap-2 p-1.5 bg-slate-200/80 rounded-2xl w-fit">
        <button
          type="button"
          onClick={() => setActiveSubTab("robots")}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition cursor-pointer ${
            activeSubTab === "robots"
              ? "bg-white text-indigo-700 shadow-xs"
              : "text-slate-600 hover:text-slate-900"
          }`}
        >
          <FileCode className="w-4 h-4" />
          <span>robots.txt Controller</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveSubTab("sitemap")}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition cursor-pointer ${
            activeSubTab === "sitemap"
              ? "bg-white text-emerald-700 shadow-xs"
              : "text-slate-600 hover:text-slate-900"
          }`}
        >
          <Globe className="w-4 h-4" />
          <span>sitemap.xml Builder ({urlCountMatch} URLs)</span>
        </button>
      </div>

      {/* ========================================================= */}
      {/* 1. ROBOTS.TXT CONTROLLER */}
      {/* ========================================================= */}
      {activeSubTab === "robots" && (
        <div className="space-y-6">
          {robotsSavedSuccess && (
            <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-xs text-emerald-800 font-bold flex items-center gap-2 shadow-xs">
              <Check className="w-4 h-4 text-emerald-600" />
              <span>robots.txt has been built, saved, and updated live at /robots.txt!</span>
            </div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Generator Form */}
            <div className="lg:col-span-5 bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs space-y-5">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <h3 className="text-sm font-black text-slate-900 flex items-center gap-2">
                  <Sliders className="w-4 h-4 text-indigo-600" />
                  <span>Rule Configuration Builder</span>
                </h3>
                <span className="text-[10px] uppercase font-bold text-slate-400 bg-slate-100 px-2 py-0.5 rounded-md">
                  Auto-Compiler
                </span>
              </div>

              {/* User-Agent */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-700">Target User-Agent</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={robotsUserAgent}
                    onChange={(e) => setRobotsUserAgent(e.target.value)}
                    placeholder="*"
                    className="flex-1 px-3 py-2 rounded-xl border border-slate-300 text-xs font-mono font-bold"
                  />
                  <select
                    value={robotsUserAgent}
                    onChange={(e) => setRobotsUserAgent(e.target.value)}
                    className="bg-slate-50 border border-slate-300 text-slate-700 rounded-xl px-2 py-2 text-xs font-semibold"
                  >
                    <option value="*">All Bots (*)</option>
                    <option value="Googlebot">Googlebot</option>
                    <option value="Bingbot">Bingbot</option>
                    <option value="Baiduspider">Baiduspider</option>
                    <option value="Yandex">Yandex</option>
                  </select>
                </div>
              </div>

              {/* Crawler Toggles */}
              <div className="space-y-3 pt-1">
                <label className="text-xs font-bold text-slate-700">Protected Directives &amp; Paths</label>

                <label className="flex items-center gap-2.5 p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={allowAllCrawling}
                    onChange={(e) => setAllowAllCrawling(e.target.checked)}
                    className="w-4 h-4 text-indigo-600 rounded"
                  />
                  <div>
                    <span className="text-xs font-bold text-slate-800 block">Allow Root Crawling (`Allow: /`)</span>
                    <span className="text-[11px] text-slate-500">Permits search engines to crawl public content</span>
                  </div>
                </label>

                <label className="flex items-center gap-2.5 p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={disallowAdmin}
                    onChange={(e) => setDisallowAdmin(e.target.checked)}
                    className="w-4 h-4 text-indigo-600 rounded"
                  />
                  <div>
                    <span className="text-xs font-bold text-slate-800 block">Block Admin Consoles (`/admin*`)</span>
                    <span className="text-[11px] text-slate-500">Hides admin panels from indexing</span>
                  </div>
                </label>

                <label className="flex items-center gap-2.5 p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={disallowApi}
                    onChange={(e) => setDisallowApi(e.target.checked)}
                    className="w-4 h-4 text-indigo-600 rounded"
                  />
                  <div>
                    <span className="text-xs font-bold text-slate-800 block">Block API Endpoints (`/api/`)</span>
                    <span className="text-[11px] text-slate-500">Prevents bots from calling extraction routes</span>
                  </div>
                </label>

                <label className="flex items-center gap-2.5 p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={disallowTemp}
                    onChange={(e) => setDisallowTemp(e.target.checked)}
                    className="w-4 h-4 text-indigo-600 rounded"
                  />
                  <div>
                    <span className="text-xs font-bold text-slate-800 block">Block Temp Folders (`/temp_downloads/`)</span>
                    <span className="text-[11px] text-slate-500">Protects transient download cache from indexation</span>
                  </div>
                </label>
              </div>

              {/* Crawl Delay & Sitemap URL */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-700">Crawl-Delay</label>
                  <select
                    value={crawlDelay}
                    onChange={(e) => setCrawlDelay(e.target.value)}
                    className="w-full px-3 py-2 rounded-xl border border-slate-300 text-xs font-medium bg-white"
                  >
                    <option value="none">None (Standard)</option>
                    <option value="1">1 second</option>
                    <option value="2">2 seconds</option>
                    <option value="5">5 seconds</option>
                    <option value="10">10 seconds</option>
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-700">Sitemap Directive</label>
                  <input
                    type="text"
                    value={sitemapUrlDirective}
                    onChange={(e) => setSitemapUrlDirective(e.target.value)}
                    placeholder="https://example.com/sitemap.xml"
                    className="w-full px-3 py-2 rounded-xl border border-slate-300 text-xs font-mono"
                  />
                </div>
              </div>

              {/* Custom Disallow Textarea */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-700">Additional Custom Disallows (one per line)</label>
                <textarea
                  rows={2}
                  value={customDisallowRules}
                  onChange={(e) => setCustomDisallowRules(e.target.value)}
                  placeholder="/private-test&#10;/beta-pages"
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 text-xs font-mono"
                />
              </div>

              {/* Build Button */}
              <button
                type="button"
                onClick={handleBuildRobots}
                className="w-full py-2.5 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-xs cursor-pointer transition active:scale-98"
              >
                <Sparkles className="w-4 h-4" />
                <span>⚡ Re-Build &amp; Compile robots.txt</span>
              </button>
            </div>

            {/* Live Code Editor Viewport */}
            <div className="lg:col-span-7 bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs flex flex-col justify-between space-y-4">
              <div>
                <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                  <div className="flex items-center gap-2">
                    <FileCode className="w-4 h-4 text-indigo-600" />
                    <h3 className="text-sm font-black text-slate-900">Live robots.txt File Editor</h3>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={handleResetRobots}
                      className="text-[11px] font-bold text-slate-500 hover:text-slate-800 p-1.5 hover:bg-slate-100 rounded-lg transition"
                      title="Reset to recommended defaults"
                    >
                      <RotateCcw className="w-3.5 h-3.5" />
                    </button>
                    <button
                      type="button"
                      onClick={handleCopyRobots}
                      className="text-[11px] font-bold text-slate-600 hover:text-indigo-600 px-2.5 py-1 rounded-lg border border-slate-200 hover:bg-indigo-50 transition flex items-center gap-1"
                    >
                      {robotsCopied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{robotsCopied ? "Copied!" : "Copy"}</span>
                    </button>
                  </div>
                </div>

                <p className="text-xs text-slate-500 mt-2">
                  You can edit the raw text directly below or generate it using the rule compiler on the left. Changes take effect on the live URL immediately upon saving.
                </p>

                {/* Editor Box */}
                <div className="mt-3 relative rounded-xl overflow-hidden border border-slate-800 bg-slate-950 font-mono text-xs shadow-inner">
                  <div className="bg-slate-900 px-4 py-2 text-[10px] text-slate-400 font-bold border-b border-slate-800 flex items-center justify-between">
                    <span>public / robots.txt</span>
                    <span>{robotsContent.length} characters • {robotsContent.split("\n").length} lines</span>
                  </div>
                  <textarea
                    rows={15}
                    value={robotsContent}
                    onChange={(e) => setRobotsContent(e.target.value)}
                    className="w-full p-4 bg-slate-950 text-emerald-400 font-mono text-xs focus:outline-none resize-y leading-relaxed"
                    spellCheck={false}
                  />
                </div>
              </div>

              {/* Action Buttons */}
              <div className="pt-2 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-3">
                <a
                  href="/robots.txt"
                  target="_blank"
                  rel="noreferrer"
                  className="text-xs font-bold text-indigo-600 hover:underline flex items-center gap-1"
                >
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span>Test / View Live Server File (/robots.txt)</span>
                </a>

                <button
                  type="button"
                  onClick={handleSaveRobots}
                  disabled={isRobotsSyncing}
                  className="w-full sm:w-auto px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-xs flex items-center justify-center gap-2 cursor-pointer transition active:scale-98 disabled:opacity-70"
                >
                  {isRobotsSyncing ? (
                    <RefreshCw className="w-4 h-4 animate-spin" />
                  ) : (
                    <Save className="w-4 h-4" />
                  )}
                  <span>Save &amp; Deploy robots.txt</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ========================================================= */}
      {/* 2. SITEMAP.XML CONTROLLER */}
      {/* ========================================================= */}
      {activeSubTab === "sitemap" && (
        <div className="space-y-6">
          {sitemapSavedSuccess && (
            <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-xs text-emerald-800 font-bold flex items-center gap-2 shadow-xs">
              <Check className="w-4 h-4 text-emerald-600" />
              <span>sitemap.xml has been built, verified, and updated live at /sitemap.xml!</span>
            </div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Sitemap Builder Settings */}
            <div className="lg:col-span-5 bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs space-y-5">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <h3 className="text-sm font-black text-slate-900 flex items-center gap-2">
                  <Globe className="w-4 h-4 text-emerald-600" />
                  <span>Sitemap XML Compiler</span>
                </h3>
                <span className="text-[10px] uppercase font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded-md">
                  Index Scanner
                </span>
              </div>

              {/* Base Domain */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-700">Site Domain / Base URL</label>
                <input
                  type="text"
                  value={sitemapDomain}
                  onChange={(e) => setSitemapDomain(e.target.value)}
                  placeholder="https://mysite.com"
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 text-xs font-mono font-bold"
                />
                <p className="text-[11px] text-slate-400">Canonical URL prefix used inside all &lt;loc&gt; tags.</p>
              </div>

              {/* Content Inclusions */}
              <div className="space-y-3 pt-1">
                <label className="text-xs font-bold text-slate-700">Included Content Streams</label>

                <label className="flex items-center gap-2.5 p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={incCorePages}
                    onChange={(e) => setIncCorePages(e.target.checked)}
                    className="w-4 h-4 text-emerald-600 rounded"
                  />
                  <div>
                    <span className="text-xs font-bold text-slate-800 block">Core System Pages</span>
                    <span className="text-[11px] text-slate-500">/, /how-it-works, /blog, /about, /contact, /privacy, /terms</span>
                  </div>
                </label>

                <label className="flex items-center gap-2.5 p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={incLanguages}
                    onChange={(e) => setIncLanguages(e.target.checked)}
                    className="w-4 h-4 text-emerald-600 rounded"
                  />
                  <div>
                    <span className="text-xs font-bold text-slate-800 block">Multilingual Variations (6 Locales)</span>
                    <span className="text-[11px] text-slate-500">Generates localized URLs for /en, /br, /es, /fr, /de, /id</span>
                  </div>
                </label>

                <label className="flex items-center gap-2.5 p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={incBlogPosts}
                    onChange={(e) => setIncBlogPosts(e.target.checked)}
                    className="w-4 h-4 text-emerald-600 rounded"
                  />
                  <div>
                    <span className="text-xs font-bold text-slate-800 block">Blog &amp; Knowledge Base Posts</span>
                    <span className="text-[11px] text-slate-500">Includes {posts.length} published blog articles</span>
                  </div>
                </label>

                <label className="flex items-center gap-2.5 p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={incCustomPages}
                    onChange={(e) => setIncCustomPages(e.target.checked)}
                    className="w-4 h-4 text-emerald-600 rounded"
                  />
                  <div>
                    <span className="text-xs font-bold text-slate-800 block">Custom Created Pages</span>
                    <span className="text-[11px] text-slate-500">Includes all published admin-created custom pages</span>
                  </div>
                </label>
              </div>

              {/* Changefreq & Priority */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-700">Change Frequency</label>
                  <select
                    value={defaultChangeFreq}
                    onChange={(e) => setDefaultChangeFreq(e.target.value as any)}
                    className="w-full px-3 py-2 rounded-xl border border-slate-300 text-xs font-medium bg-white"
                  >
                    <option value="daily">Daily</option>
                    <option value="weekly">Weekly</option>
                    <option value="monthly">Monthly</option>
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-700">Root Priority</label>
                  <select
                    value={defaultPriority}
                    onChange={(e) => setDefaultPriority(e.target.value)}
                    className="w-full px-3 py-2 rounded-xl border border-slate-300 text-xs font-medium bg-white"
                  >
                    <option value="1.0">1.0 (Highest)</option>
                    <option value="0.9">0.9</option>
                    <option value="0.8">0.8</option>
                    <option value="0.7">0.7</option>
                  </select>
                </div>
              </div>

              {/* Build Button */}
              <button
                type="button"
                onClick={handleBuildSitemap}
                className="w-full py-2.5 px-4 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-xs cursor-pointer transition active:scale-98"
              >
                <Sparkles className="w-4 h-4" />
                <span>⚡ Re-Build &amp; Scan Pages into sitemap.xml</span>
              </button>
            </div>

            {/* Live XML Code Viewport */}
            <div className="lg:col-span-7 bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs flex flex-col justify-between space-y-4">
              <div>
                <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                  <div className="flex items-center gap-2">
                    <Globe className="w-4 h-4 text-emerald-600" />
                    <h3 className="text-sm font-black text-slate-900">Live sitemap.xml XML Document</h3>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={handleDownloadSitemap}
                      className="text-[11px] font-bold text-slate-600 hover:text-emerald-700 px-2.5 py-1 rounded-lg border border-slate-200 hover:bg-emerald-50 transition flex items-center gap-1 cursor-pointer"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Download XML</span>
                    </button>
                    <button
                      type="button"
                      onClick={handleCopySitemap}
                      className="text-[11px] font-bold text-slate-600 hover:text-indigo-600 px-2.5 py-1 rounded-lg border border-slate-200 hover:bg-indigo-50 transition flex items-center gap-1 cursor-pointer"
                    >
                      {sitemapCopied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{sitemapCopied ? "Copied!" : "Copy"}</span>
                    </button>
                  </div>
                </div>

                <div className="flex items-center justify-between mt-2 text-xs">
                  <span className="text-slate-500">
                    Directly editable standard XML conformant with Sitemaps 0.9 schema.
                  </span>
                  <span className="font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200 text-[11px]">
                    {urlCountMatch} URLs Indexed
                  </span>
                </div>

                {/* Editor Box */}
                <div className="mt-3 relative rounded-xl overflow-hidden border border-slate-800 bg-slate-950 font-mono text-xs shadow-inner">
                  <div className="bg-slate-900 px-4 py-2 text-[10px] text-slate-400 font-bold border-b border-slate-800 flex items-center justify-between">
                    <span>public / sitemap.xml</span>
                    <span>{sitemapContent.length} bytes • {urlCountMatch} URL nodes</span>
                  </div>
                  <textarea
                    rows={15}
                    value={sitemapContent}
                    onChange={(e) => setSitemapContent(e.target.value)}
                    className="w-full p-4 bg-slate-950 text-cyan-300 font-mono text-xs focus:outline-none resize-y leading-relaxed"
                    spellCheck={false}
                  />
                </div>
              </div>

              {/* Action Buttons */}
              <div className="pt-2 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-3">
                <a
                  href="/sitemap.xml"
                  target="_blank"
                  rel="noreferrer"
                  className="text-xs font-bold text-emerald-700 hover:underline flex items-center gap-1"
                >
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span>Test / View Live Server File (/sitemap.xml)</span>
                </a>

                <button
                  type="button"
                  onClick={handleSaveSitemap}
                  disabled={isSitemapSyncing}
                  className="w-full sm:w-auto px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-xs flex items-center justify-center gap-2 cursor-pointer transition active:scale-98 disabled:opacity-70"
                >
                  {isSitemapSyncing ? (
                    <RefreshCw className="w-4 h-4 animate-spin" />
                  ) : (
                    <Save className="w-4 h-4" />
                  )}
                  <span>Save &amp; Deploy sitemap.xml</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
